### ISSUE TITLE
我還是不能push阿

### ISSUE THREAD

**Issue by dy93** [HappyCompanions/LeetCode#2]
#Q_Q

**Comment by dy93** [comment]
@hwchiu 踹共

**Comment by dy93** [comment]
可以惹!

**Comment by hwchiu** [comment]
竟然寫兩個檔案
dy93 <notifications@github.com>於 2017年1月13日 週五，下午11:03寫道：

**Comment by dy93** [comment]
一個是pr一個是issue不一樣R

**Comment by hwchiu** [comment]
我說程式碼 顆顆
dy93 <notifications@github.com>於 2017年1月13日 週五，下午11:07寫道：
